# SwiftLint Configuration for Agora
# Based on Apple's style guidelines and Swift 6.2 best practices

# Paths to include/exclude
included:
  - Packages
  - Resources
  - Tests

excluded:
  - Packages/ThirdParty
  - OpenAPI/Generated
  - .build

# Rules to enable/disable
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  Agora
                    \/\/
                    \/\/  Created by .* on \d{4}\.
                    \/\/

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - url
    - api
    - ui
    - db
    - id

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 60

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import
